# Generated by Django 4.2.4 on 2023-08-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScripMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('expiry', models.TextField()),
                ('strike', models.TextField()),
                ('lotsize', models.TextField()),
                ('instrumenttype', models.TextField()),
                ('exch_seg', models.TextField()),
                ('tick_size', models.TextField()),
            ],
        ),
    ]
